name: Frontend Bundle Stats

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-bundle-stats.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build with stats
        run: npx webpack --mode production --profile --json > build-stats.json

      - name: Upload stats artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpack-build-stats
          path: frontend/build-stats.json
          retention-days: 7

      - name: Warn on large main bundle
        run: |
          SIZE=$(node -e "const f=require('./build-stats.json'); const main=(f.assets||[]).filter(a=>/main.*js$/.test(a.name))[0]; console.log(main?main.size:0)")
          echo "Main bundle size: $SIZE bytes"
          if [ "$SIZE" -gt 500000 ]; then echo "::warning ::Main bundle exceeds 500KB"; fi