name: Security Audit

on:
  workflow_dispatch:
  schedule:
    # Run daily at 03:17 UTC (arbitrary staggered time)
    - cron: '17 3 * * *'

permissions:
  contents: read

concurrency:
  group: security-audit
  cancel-in-progress: false

jobs:
  audit:
    name: Dependency Audit (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install dependencies (CI)
        run: npm ci

      - name: Production security audit (fail on high)
        run: |
          npm audit --production --audit-level=high || (echo "High severity vulnerabilities found" && exit 1)

      - name: List outdated (informational)
        run: |
          npm outdated || true

  summary:
    name: Audit Summary
    runs-on: ubuntu-latest
    needs: audit
    steps:
      - name: Summary
        run: echo "Security audit completed for backend and frontend projects."
